### ISSUE TITLE
Probably User Error

### ISSUE THREAD

**Issue by MIOResNet** [ox-it/munki-staging#21] opened 2016-04-01 15:01 UTC
I am having an issue with running munki-staging.py

Every time it is run I get an error 401. I generated the token multiple times to see if that makes a difference or not. 

I am unsure if the variables for "token", "key", and "boardid" should be surrounded by single quotes or not. From reading the url it adds a "%27" before and after the token and key. 

<img width="813" alt="munkistaging401error" src="https://cloud.githubusercontent.com/assets/15675845/14210861/99ea144c-f7f0-11e5-944a-826b5848cc8e.png">

> HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://trello.com/1/boards/96OI8FLj/..........

**Comment by oucsaw** [comment] 2016-04-01 16:33
I've quickly tested this, and in the current version putting quotes around `key`, `token`, and `boardid` will break things giving a 401 error similar to the above. 

This will be fixed shortly and allow both quoted and unquoted values, with a tweak to the documentation to hint that quotes should not be used.

**Comment by MIOResNet** [comment] 2016-04-01 16:47
Thank you for looking into this so quickly. Without the quotes around token or key we get a different error. We have been banging our heads against the wall trying to get it working the past couple of days and can't seem to figure out what is going on.

The url that Trello wants to use is https://trello.com/1/board/substitutewiththeboardid?key=substitutewithyourapplicationkey&token=substitutethispartwiththeauthorizationtokenthatyougotfromtheuser

But from what I can tell, the url that is generated puts a "/" between boardid and the rest of the link as well as it adds "cards" & "%27".

https://trello.com/1/board/substitutewiththeboardid**/**?key=substitutewithyourapplicationkey&token=substitutethispartwiththeauthorizationtokenthatyougotfromtheuser

![munkistaging-not_recognised_list](https://cloud.githubusercontent.com/assets/15675845/14213668/e25c1c94-f7fe-11e5-8980-942d0b7443af.png)

**Comment by oucsaw** [comment] 2016-04-01 17:16
The output above from the run looks okay; the script seems to be talking to your trello board successfully as it seems to be finding trello cards (the three lines `XXX card <name> not in recognised list` mean that the script has connected to trello and found these trello cards but they are not in lists it knows about - which is not a problem, as it then ignores these).

Have you defined a repository section in your config ? It may not be entirely obvious from the instructions, but you will need at last one section like:

```
[munki_repo_NAME]
repo_path=/path/to/repository
```

in the configuration file.

**Comment by MIOResNet** [comment] 2016-04-01 22:44
First, thank you for resolving the issues right away. 

We did specify our repo once. In the beginning of the config file.

There is the other section that ask for multiple munki repositories. 

What we are stuck on is how it detects what cards are suppose to be where. And if the cards should auto generate.

**Comment by oucsaw** [comment] 2016-04-04 10:44
I'm had a look at this over the weekend and this morning and fixed some bugs  and tweaked some things in the latest commit that may or may not be of use.

You can now run this as `munki-staging.py --showconfig` and it will list the Trello boards that the script will use and then exit. There is also more checking that things are setup as the script expects.

If you are using a config file then the minimum configuration is

```
[main]
boardid=ua6oor0oL
key=cf3e10a51fd05ef4a1944c7ccd713aa6
token=6b8a8177589e02994c5183a881b6c91f6709f6dcc6711591c05eb3def190e0

[munki_repo_default]
repo_path=/Volumes/Munki/Software
```

(note the trello information has been randomly genereated, and will not work)  which will the expect a trello board with at least the following lists:
- To Development
- Development
- To Testing
- Testing
- To Production
- Production
  If you would like more (or fewer) boards then these will need to be defined in the configuration file - there should be examples of this in both the README.md file and the configuration file template (munki-staging.cfg-template).

The Trello cards are automatically added - one for each package in the Munki repository.  They will be added by the script if they are missing.  The are created in the list that matches the Munki catalog they are in; so if a package is in the Munki catalog 'development' it will get added to the Trello list Development (assuming the default config is in place).

**Comment by MIOResNet** [comment] 2016-04-08 21:11
This helped a lot this week. We were able to generate the cards and were able to successfully run everything once. We are only running into one problem that we can't fix.

Every time we move a card to a "ToDevelopment" or any other "ToX" board it gives an AttributeError: 'NoneType' object has no attribute 'name'. 

After it errors out it doesn't run "makecatalog", however it does change the plist file of the application to the new catalog. 

![screen shot 2016-04-08 at 4 09 45 pm](https://cloud.githubusercontent.com/assets/15675845/14397692/9b33fa98-fda4-11e5-8c2e-eed48308a4c1.png)

**Comment by oucsaw** [comment] 2016-04-09 12:03
Unfortunately, I can't reproduce this issue using the test configurations I have. Unfortunately, this probably means that this issue is exposed by a certain set of configuration options.

Would it be possible for you to share the configuration file you are using (clearly, with the Trello board id, key, token and any paths redacted) and any command line arguments passed to the script ? This would hopefully allow me to reproduce the problem, and resolve the underlying issue. 

Meanwhile, I've pushed some extra debugging for this issue into this repository, which may help track down this bug.

**Comment by oucsaw** [comment] 2016-04-09 12:06
(I forgot to mention: could you also provide the output from the script with the new codebase, too, as this should also give some hints as to what is going on)

**Comment by MIOResNet** [comment] 2016-04-11 15:37
Actually we figured it out. The issue was user error. When setting up the Munki Catalog Sections we made munki_repo= the path to our repo instead of the name "main" or "retired".

**Comment by oucsaw** [comment] 2016-04-11 16:11
Well done for getting to the bottom of this problem!

**Closed as completed** 2016-11-16 12:34 UTC
